package com.xiaomi.example.pojo;

public class UserDOKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.email
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}