package com.xiaomi.example.dao;

import com.xiaomi.example.pojo.OrderDO;
import com.xiaomi.example.pojo.OrderDOExample;

import java.util.List;

public interface OrderDODAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int countByExample(OrderDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int deleteByExample(OrderDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    Integer insert(OrderDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    Integer insertSelective(OrderDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    List selectByExample(OrderDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    OrderDO selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int updateByExampleSelective(OrderDO record, OrderDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int updateByExample(OrderDO record, OrderDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int updateByPrimaryKey(OrderDO record);
}