package com.xiaomi.example.dal.dataobject;

public class BookDO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.book_isbn
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private String bookIsbn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.book_name
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private String bookName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.publish
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private String publish;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.author
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private String author;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.count
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.remark
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_bookinfo.price
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    private Double price;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.book_isbn
     *
     * @return the value of tb_bookinfo.book_isbn
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.book_isbn
     *
     * @param bookIsbn the value for tb_bookinfo.book_isbn
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.book_name
     *
     * @return the value of tb_bookinfo.book_name
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.book_name
     *
     * @param bookName the value for tb_bookinfo.book_name
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.publish
     *
     * @return the value of tb_bookinfo.publish
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public String getPublish() {
        return publish;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.publish
     *
     * @param publish the value for tb_bookinfo.publish
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setPublish(String publish) {
        this.publish = publish == null ? null : publish.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.author
     *
     * @return the value of tb_bookinfo.author
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.author
     *
     * @param author the value for tb_bookinfo.author
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.count
     *
     * @return the value of tb_bookinfo.count
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.count
     *
     * @param count the value for tb_bookinfo.count
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.remark
     *
     * @return the value of tb_bookinfo.remark
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.remark
     *
     * @param remark the value for tb_bookinfo.remark
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_bookinfo.price
     *
     * @return the value of tb_bookinfo.price
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_bookinfo.price
     *
     * @param price the value for tb_bookinfo.price
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return "BookDO{" +
                "bookIsbn='" + bookIsbn + '\'' +
                ", bookName='" + bookName + '\'' +
                ", publish='" + publish + '\'' +
                ", author='" + author + '\'' +
                ", count=" + count +
                ", remark='" + remark + '\'' +
                ", price=" + price +
                '}';
    }
}