package com.xiaomi.example.dal.dataobject;

public class OrderDO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_order.order_id
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_order.order_no
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_order.book_isbn
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private String bookIsbn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_order.count
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_order.remark
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private String remark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_order.order_id
     *
     * @return the value of tb_order.order_id
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_order.order_id
     *
     * @param orderId the value for tb_order.order_id
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_order.order_no
     *
     * @return the value of tb_order.order_no
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_order.order_no
     *
     * @param orderNo the value for tb_order.order_no
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_order.book_isbn
     *
     * @return the value of tb_order.book_isbn
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_order.book_isbn
     *
     * @param bookIsbn the value for tb_order.book_isbn
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_order.count
     *
     * @return the value of tb_order.count
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_order.count
     *
     * @param count the value for tb_order.count
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_order.remark
     *
     * @return the value of tb_order.remark
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_order.remark
     *
     * @param remark the value for tb_order.remark
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}