package com.xiaomi.example.dal.dataobject;

public class UserDO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.email
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.gender
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    private String gender;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_user.password
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    private String password;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.gender
     *
     * @return the value of tb_user.gender
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.gender
     *
     * @param gender the value for tb_user.gender
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @ibatorgenerated Tue Feb 28 18:27:05 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    @Override
    public String toString() {
        return "UserDO{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", email='" + email + '\'' +
                ", gender='" + gender + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}