package com.xiaomi.example.dal.dao.impl;

import com.xiaomi.example.dal.dao.OrderDAO;
import com.xiaomi.example.dal.dataobject.OrderDO;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrderDAOImpl extends SqlMapClientDaoSupport implements OrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public OrderDAOImpl() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int deleteByPrimaryKey(Integer orderId) {
        OrderDO key = new OrderDO();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("tb_order_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer insert(OrderDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_order_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer insertSelective(OrderDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_order_insertSelective", record);
        return (Integer) newKey;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public OrderDO selectByPrimaryKey(Integer orderId) {
        OrderDO key = new OrderDO();
        key.setOrderId(orderId);
        OrderDO record = (OrderDO) getSqlMapClientTemplate().queryForObject("tb_order_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int updateByPrimaryKeySelective(OrderDO record) {
        int rows = getSqlMapClientTemplate().update("tb_order_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int updateByPrimaryKey(OrderDO record) {
        int rows = getSqlMapClientTemplate().update("tb_order_updateByPrimaryKey", record);
        return rows;
    }

}