package com.xiaomi.example.dal.dao;

import com.xiaomi.example.dal.dataobject.BookDO;

public interface BookDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_bookinfo
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    int deleteByPrimaryKey(String bookIsbn);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_bookinfo
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    String insert(BookDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_bookinfo
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    String insertSelective(BookDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_bookinfo
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    BookDO selectByPrimaryKey(String bookIsbn);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_bookinfo
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    int updateByPrimaryKeySelective(BookDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_bookinfo
     *
     * @ibatorgenerated Tue Feb 28 16:46:40 CST 2017
     */
    int updateByPrimaryKey(BookDO record);
}