package com.xiaomi.example.dal.dao;

import com.xiaomi.example.dal.dataobject.OrderDO;

public interface OrderDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    Integer insert(OrderDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    Integer insertSelective(OrderDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    OrderDO selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    int updateByPrimaryKey(OrderDO record);
}