package com.xiaomi.example.dao;

import com.xiaomi.example.pojo.OrderDO;
import com.xiaomi.example.pojo.OrderDOExample;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import java.util.List;

public class OrderDODAOImpl extends SqlMapClientDaoSupport implements OrderDODAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public OrderDODAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int countByExample(OrderDOExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int deleteByExample(OrderDOExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int deleteByPrimaryKey(Integer orderId) {
        OrderDO key = new OrderDO();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("tb_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer insert(OrderDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_order.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public Integer insertSelective(OrderDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_order.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public List selectByExample(OrderDOExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public OrderDO selectByPrimaryKey(Integer orderId) {
        OrderDO key = new OrderDO();
        key.setOrderId(orderId);
        OrderDO record = (OrderDO) getSqlMapClientTemplate().queryForObject("tb_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int updateByExampleSelective(OrderDO record, OrderDOExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int updateByExample(OrderDO record, OrderDOExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int updateByPrimaryKeySelective(OrderDO record) {
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    public int updateByPrimaryKey(OrderDO record) {
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:29:31 CST 2017
     */
    private static class UpdateByExampleParms extends OrderDOExample {
        private Object record;

        public UpdateByExampleParms(Object record, OrderDOExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}