package com.xiaomi.example.dao;

import com.xiaomi.example.pojo.OrederDO;
import com.xiaomi.example.pojo.OrederDOExample;

import java.util.List;

public interface OrederDODAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int countByExample(OrederDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int deleteByExample(OrederDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    Integer insert(OrederDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    Integer insertSelective(OrederDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    List selectByExample(OrederDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    OrederDO selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int updateByExampleSelective(OrederDO record, OrederDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int updateByExample(OrederDO record, OrederDOExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int updateByPrimaryKeySelective(OrederDO record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    int updateByPrimaryKey(OrederDO record);
}