package com.xiaomi.example.dao;

import com.xiaomi.example.pojo.OrederDO;
import com.xiaomi.example.pojo.OrederDOExample;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import java.util.List;

public class OrederDODAOImpl extends SqlMapClientDaoSupport implements OrederDODAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public OrederDODAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int countByExample(OrederDOExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int deleteByExample(OrederDOExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int deleteByPrimaryKey(Integer orderId) {
        OrederDO key = new OrederDO();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("tb_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public Integer insert(OrederDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_order.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public Integer insertSelective(OrederDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_order.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public List selectByExample(OrederDOExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public OrederDO selectByPrimaryKey(Integer orderId) {
        OrederDO key = new OrederDO();
        key.setOrderId(orderId);
        OrederDO record = (OrederDO) getSqlMapClientTemplate().queryForObject("tb_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int updateByExampleSelective(OrederDO record, OrederDOExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int updateByExample(OrederDO record, OrederDOExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int updateByPrimaryKeySelective(OrederDO record) {
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    public int updateByPrimaryKey(OrederDO record) {
        int rows = getSqlMapClientTemplate().update("tb_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_order
     *
     * @ibatorgenerated Thu Mar 23 10:25:38 CST 2017
     */
    private static class UpdateByExampleParms extends OrederDOExample {
        private Object record;

        public UpdateByExampleParms(Object record, OrederDOExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}