package com.xiaomi.example.dao;

import com.xiaomi.example.pojo.UserDO;
import com.xiaomi.example.pojo.UserDOExample;
import com.xiaomi.example.pojo.UserDOKey;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import java.util.List;

public class UserDODAOImpl extends SqlMapClientDaoSupport implements UserDODAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public UserDODAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int countByExample(UserDOExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int deleteByExample(UserDOExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int deleteByPrimaryKey(UserDOKey key) {
        int rows = getSqlMapClientTemplate().delete("tb_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public Integer insert(UserDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_user.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public Integer insertSelective(UserDO record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_user.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public List selectByExample(UserDOExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public UserDO selectByPrimaryKey(UserDOKey key) {
        UserDO record = (UserDO) getSqlMapClientTemplate().queryForObject("tb_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int updateByExampleSelective(UserDO record, UserDOExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int updateByExample(UserDO record, UserDOExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int updateByPrimaryKeySelective(UserDO record) {
        int rows = getSqlMapClientTemplate().update("tb_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    public int updateByPrimaryKey(UserDO record) {
        int rows = getSqlMapClientTemplate().update("tb_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_user
     *
     * @ibatorgenerated Thu Mar 23 10:22:06 CST 2017
     */
    private static class UpdateByExampleParms extends UserDOExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserDOExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}